### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mendelct** [pnemonic78/HalachicTimes#118]
Tried to compile in Android Studio got the following error AddLocationActivity is not abstract and does not override abstract method onCreate() in ThemeCallbacks. What am I missing?

**Comment by pnemonic78** [comment]
Are you using master branch?

onCreate() was renamed to onPreCreate

From: mendelct ***@***.***>
Date: Wednesday, 30 November 2022 at 21:32
To: pnemonic78/HalachicTimes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pnemonic78/HalachicTimes] Compile error (Issue #118)

Tried to compile in Android Studio got the following error AddLocationActivity is not abstract and does not override abstract method onCreate() in ThemeCallbacks. What am I missing?

**Comment by mendelct** [comment]
Git was not cloning the latest version

**Comment by mendelct** [comment]
a simple git submodule update --remote seems to have solved the issue
