### ISSUE TITLE
Upon enabling reminders, "Remind on Sunday" et seq. remain grayed out temporarily

### ISSUE THREAD

**Issue by unforgettableid** [pnemonic78/HalachicTimes#120]
### Steps to reproduce

1.  Open the "Halachic Times" app.
1.  Tap the three dots.
1.  Tap "Settings".
1.  Tap "Halachic Prayer Times".
1.  Tap "Dawn".
1.  Tap "Reminder".
1.  Change the Reminder setting from "Off" to "1 minute before".

### Actual results

1.  "Remind on Sunday" through "Remind on Saturday and Yom Tov" all remain disabled (greyed out).  To enable them, you must tap the Back button then tap "Dawn" again.

### Hoped-for results

1.  I was hoping that "Remind on Sunday" through "Remind on Saturday and Yom Tov" would immediately become usable, as soon as I changed the Reminder setting from "Off" to "1 minute before".

### Notes

I'm using Halachic Times 13.17 on an old LG G5 LG-H831 running Android 8.0.0 "Oreo".

Thank you for all the volunteer time and effort you've put into this useful app!  It's a kind act of _chesed_ to the community.

**Comment by pnemonic78** [comment]
fixed in commit 89cfb15f0dc83aacf0c347b912d80ab208db8669

**Comment by unforgettableid** [comment]
Appreciated!

Verified fixed in version 13.20.
