### ISSUE TITLE
Android 13: Alarm Fires Up & Appears But Has No Audio

### ISSUE THREAD

**Issue by josagan** [pnemonic78/HalachicTimes#122]
Alarm Fires Up & Appears But Has No Audio

OS: Android 13

Build: version T1TGNS33.60-55-3-5. 
(includes updates of Android security patches through 1 September 2023)

Phone: Motorola Moto G Stylus 5G 2023

App Settings > Halachic Prayer Times
Sunrise
Afternoon Prayers
Nightfall
All are set to:
Reminder: On time
Remind on: Sunday to Friday and Saturday and Yom Tov

App Settings > General > Reminder
Reminder type:  Alarm
Reminder ringtone: Argon  (one of the stock Android alarm tones)

Android settings > Apps > Halachic Prayer Times > Notifications
Show notifications: On
Default: Selected
Pop on screen: On
Sound: Argon.ogg
Lock screen: Show all notification content

**Comment by pnemonic78** [comment]
Which app version?

**Comment by josagan** [comment]
App version 13.22

I just noticed that when the alarm fires (see screenshot) it does vibrate the phone, but still no audio. 

![Alarm_Screenshot_25](https://github.com/pnemonic78/HalachicTimes/assets/153572018/6e9c0832-034f-4958-b2b0-28561a77ad33)

**Comment by pnemonic78** [comment]
extra check for permission in commit 52f66c27a045d68da02bb1b7fcef12170a501355

**Comment by josagan** [comment]
pnemonic78 thanks for working on this, I appreciate it. 

Unfortunately, it is still not working. I tried clearing cache and storage, uninstalling, and reinstalling to no avail. It still has the same behavior: Fires up, vibrates the phone, but no audio.

**Comment by pnemonic78** [comment]
fixed in commit 217db05257b5404153eb658aa63ddc5831fd11e0

**Comment by josagan** [comment]
You were successful with v13.24! Mazel Tov! Thank you very much for all your hard work and for creating this app, I appreciate it.
